name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      run: sudo apt-get install zip

    - name: Create Zip file
      run: zip -r logseq-plugin-copy-page-properties.zip ./dist/* ./package.json ./README.md

    - name: Install GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.4.0/gh_2.4.0_linux_amd64.tar.gz | sudo tar xz -C /usr/local/bin --strip-components=2 gh_2.4.0_linux_amd64/bin/gh

    - name: Authenticate with GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Release
      run: |
        gh release create ${{ github.ref }} logseq-plugin-copy-page-properties.zip -t "Release ${{ github.ref }}" -n "Release notes"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}